### ISSUE TITLE
V2 Changes are returning 404 errors

### ISSUE THREAD

**Issue by nickjohnson22** [alpacahq/example-scalping#13]
I didn't modify any of the code and ran this script as is. Here is the output.

```
https://stream.data.alpaca.markets
2021-03-04 10:18:23,356:stream.py:295:INFO:alpaca_trade_api.stream:started trading stream
2021-03-04 10:18:23,371:stream.py:196:INFO:alpaca_trade_api.stream:started data stream
2021-03-04 10:18:23,464:stream.py:213:WARNING:root:websocket error, restarting connection: server rejected WebSocket connection: HTTP 404
2021-03-04 10:18:23,606:stream.py:282:INFO:alpaca_trade_api.stream:connected to: wss://paper-api.alpaca.markets/stream/
2021-03-04 10:18:26,569:stream.py:213:WARNING:root:websocket error, restarting connection: server rejected WebSocket connection: HTTP 404
2021-03-04 10:18:29,657:stream.py:213:WARNING:root:websocket error, restarting connection: server rejected WebSocket connection: HTTP 404
Traceback (most recent call last):
  File "D:\Users\nickjohnson\PycharmProjects\alpaca\venv\lib\site-packages\alpaca_trade_api\stream.py", line 201, in _run_forever
    await self._start_ws()
  File "D:\Users\nickjohnson\PycharmProjects\alpaca\venv\lib\site-packages\alpaca_trade_api\stream.py", line 179, in _start_ws
    await self._connect()
  File "D:\Users\nickjohnson\PycharmProjects\alpaca\venv\lib\site-packages\alpaca_trade_api\stream.py", line 50, in _connect
    extra_headers={'Content-Type': 'application/msgpack'})
  File "D:\Users\nickjohnson\PycharmProjects\alpaca\venv\lib\site-packages\websockets\client.py", line 547, in __await_impl__
    extra_headers=protocol.extra_headers,
  File "D:\Users\nickjohnson\PycharmProjects\alpaca\venv\lib\site-packages\websockets\client.py", line 296, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: server rejected WebSocket connection: HTTP 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Users\nickjohnson\PycharmProjects\alpaca\venv\lib\site-packages\alpaca_trade_api\stream.py", line 397, in _run_forever
    self._data_ws._run_forever())
  File "D:\Users\nickjohnson\PycharmProjects\alpaca\venv\lib\site-packages\alpaca_trade_api\stream.py", line 208, in _run_forever
    raise ConnectionError("max retries exceeded")
ConnectionError: max retries exceeded

Process finished with exit code 1
```

**Comment by camelpac** [comment]
Hi, just executed it:
![image](https://user-images.githubusercontent.com/78740792/110002688-598f8180-7d1e-11eb-97b5-7bd8efdc37ba.png)

make sure your credentials are set correctly and if you're using the paper trading then the api endpoint too (base_url)

**Comment by nickjohnson22** [comment]
The issue turned out to be that in the stream set up I was using capitalized SIP, instead of sip.
